### ISSUE TITLE
Is that what you want?

### ISSUE THREAD

**Issue by 239573049** [JinShil/BlazorWebView#1]
https://github.com/tryphotino/photino.Blazor

Photino is a lightweight open-source framework for building native,
cross-platform desktop applications with Web UI technology.

Photino.Blazor builds on Photino.NET to add Blazor capabilities.

Photino uses the OSs built-in WebKit-based browser control for Windows, macOS and Linux. Photino is the lightest cross-platform framework. Compared to Electron, a Photino app is up to 110 times smaller! And it uses far less system memory too!

**Comment by JinShil** [comment]
There are several problems with Photino:

- It requires one to compile native C++ code before anything will work
- I couldn't get it to work on ARM Linux
- It is way over-engineered and partitioned into too many disparate pieces
- It does not appear to be maintained well by the authors

**Comment by 239573049** [comment]
Is arm supported?

**Comment by JinShil** [comment]
Yes this project will run on an ARM Linux device like the Raspberry Pi.

**Comment by 239573049** [comment]
Thanks, I'm running it in arm

**Comment by 239573049** [comment]
It only supports Linux?

**Comment by JinShil** [comment]
Yes, it only supports Linux.  If you want Windows or other platforms, you should probably consider Maui.  Maui doesn't support Linux, so this project fills that void.

**Comment by 239573049** [comment]
However, it is difficult to maintain such a project. Have you considered supporting Win, mac and other platforms?Instead of photino

**Comment by JinShil** [comment]
If I need Windows, I'll typically just use WPF or WinForms and their WebView2 implementations.  I have no need for Mac.  See https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0 if you need support for those platforms.  This project covers Linux, which for some reason Microsoft choose to leave out.

If you are creating an applications that needs to run on Windows, Mac, Linux, and Android, you'll probably have to find a way to mix this project with the aforementioned Blazor Hybrid implementations from Microsoft.

**Comment by 239573049** [comment]
Although can be used, but not unified, use will be some trouble

**Comment by JinShil** [comment]
It can be unified by putting your application in a library and then referencing it from your Maui, Winforms, WPF, or Linux projects with the Linux project utilizing this project.  I have not prepared such an implementation so it just works out of the box; that's out of scope for what I'm trying to achieve with this project.  If the need arises for me, then I'll tackle that, but right now I don't have such a need.

**Comment by 239573049** [comment]
Ok, thank you
