### ISSUE TITLE
libgtk.dll

### ISSUE THREAD

**Issue by cedric56** [JinShil/BlazorWebView#12]
Hi i have this exception when i try to load the application, can you provide a way to remove it.

![image](https://github.com/user-attachments/assets/852da154-fbc0-4461-ac24-9d3d1a584733)

**Comment by cedric56** [comment]
I try this but it's unable to solve the problem
sudo apt -y install libgtk-4-1

**Comment by cedric56** [comment]
I was trying to launch in windows.
 Now, i get the following error on wsl and i don't know how to fix the error. Can you provide a way ? thanks

/mnt/c/Users/cedri/Documents/Avalonia/App.Sample.Linux/bin/Debug/net8.0/runtimes/linux-x64/native/GObject: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.7/GObject: cannot open shared object file: No such file or directory
/mnt/c/Users/cedri/Documents/Avalonia/App.Sample.Linux/bin/Debug/net8.0/GObject: cannot open shared object file: No such file or directory
/mnt/c/Users/cedri/Documents/Avalonia/App.Sample.Linux/bin/Debug/net8.0/runtimes/linux-x64/native/libGObject: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.7/libGObject: cannot open shared object file: No such file or directory
/mnt/c/Users/cedri/Documents/Avalonia/App.Sample.Linux/bin/Debug/net8.0/libGObject: cannot open shared object file: No such file or directory

**Comment by JinShil** [comment]
It looks like you are running in WSL from a directory that is actually on your Windows computer, but mounted at `/mnt/c/`.  Try copying your files to you the actual Linux file system and run from there.

**Comment by cedric56** [comment]
Hi, thanks for your response. Not i have an exception in Microsoft.Extensions.FileProviders.PhysicalFileProvider, The path must be absolute. (Parameter 'root').  I'm not sure if it has anything to do with your project.

**Comment by JinShil** [comment]
Please provide information about what platform you are running on (i.e. WSL, Ubuntu, etc...).  And please let me know how I can reproduce the issue.

**Comment by cedric56** [comment]
I am on windows 11, i try to launch with wsl. I try with your sample and i have this exception Permission denied. With my project avalonia, i have this the exception on PhysicalFileProvider, let me know how kind of information you want. Thanks for your time.
![image](https://github.com/user-attachments/assets/5a78112b-d79d-4bb8-9845-c42041a62340)

**Comment by JinShil** [comment]
The code in this project does not use Avalonia.  If you run the code in this project without Avalonia, does the problem still occur?  Please give me a reproduction procedure that does not involve Avalonia.

**Comment by cedric56** [comment]
If i launch your sample, i have the error. I am on Windows 11 and i launch from wsl (Ubuntu distribution). Net8.0.
![image](https://github.com/user-attachments/assets/38a6c89c-d48f-407a-81bf-1057dde404a2)

**Comment by JinShil** [comment]
I don't have access to a WSL instance at the moment, but I just tested in a Debian virtual machine, and it works fine.

How are you running the project.? The following procedure should work from WSL:
```
git clone https://github.com/JinShil/BlazorWebView.git
cd BlazorWebView/WebKitGtk.Test
dotnet run
```

EDIT:  I think the error you are seeing is because you are not running from within the correct directory.
