### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by yasmoradi** [JinShil/BlazorWebView#5]
Is it possible to run this project on Windows? (Because it seems to be based on Gtk)

**Comment by JinShil** [comment]
No, I'm afraid it will not run on Windows, as it was only designed to address the shortcoming of Blazor Hybrid applications on Linux not be supported by Microsoft (for no good reason, in my opinion).

If you are developing an application that needs to run on Windows and Linux, the proper approach would be to put your application in library, and then make a separate Windows project and a separate Linux project that have project references to your application library.  You'll just need a small amount of boilerplate code in both the Windows and Linux projects.  The bulk of your code will then go in your application library and should be portable to both the Windows and Linux projects.  It's actually quite simple to do.  Maybe I'll modify this repository with a demonstration of that at a future date.  Or, I'd be happy to accept a pull request from someone that wishes to do that for us.

**Comment by yasmoradi** [comment]
I see, what about wslg? In order to allow developers within visual studio

**Comment by JinShil** [comment]
I think this project should already work on WSLG.  Does it not?

**Comment by yasmoradi** [comment]
Maybe the app runs, but I wasn't able to debug it the way I debug other projects on wsl
I'll file an issue
