### ISSUE TITLE
Project status and Nuget Package

### ISSUE THREAD

**Issue by yasmoradi** [JinShil/BlazorWebView#6]
What's the project status? Do we expect to see a nuget package for it in near future?

**Comment by czirok** [comment]
Although we always need to be optimistic, I currently don’t believe that this will happen in the near future. 😊

**Comment by JinShil** [comment]
This project is being maintained every so often.  Everything I need from it currently works, so I'm just keeping it running.

I don't have plans at this time to create a nuget package for this.  I've never published a nuget package before, so I'm not sure what that would entail and how much maintenance it would require.  

I have no objections to anyone forking this repository, taking ownership of it, and publishing a nuget repository themselves.  Then I'd be happy to use their nuget package and retire this repository.  It'd be a welcome relief.  If it's something you want to do, go for it.

**Comment by JinShil** [comment]
I believe I've answered this question, so closing.  Please reopen if there is anything further to discuss.
